# This docker-compose file sets up two services: kobuki and lidar_node.
# The kobuki service runs the Kobuki robot base, while the lidar_node service runs
# the SLAMTEC LIDAR node. Both services are connected to a custom Docker network
# named ros_network to facilitate communication between them.
services:
  kobuki:
    image: crl/kobuki:humble
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ros2 launch kobuki augs_kobuki_node.launch.py
    restart: unless-stopped
    networks:
      - ros_network
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/cyclonedds.xml
    privileged: true
    devices:
      - /dev/kobuki:/dev/kobuki

  lidar_node:
    build:
      context: .
      dockerfile: slam.Dockerfile
    command: ros2 launch slam sllidar_with_transform.launch.py
    networks:
      - ros_network
    ports:
      - "8765:8765"
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/cyclonedds.xml
    privileged: true
    devices:
      - /dev/rplidar:/dev/rplidar
  # lidar_node:
  #   build:
  #     context: .
  #     dockerfile: lidar.Dockerfile
  #   networks:
  #     - ros_network
  #   environment:
  #     - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
  #     - CYCLONEDDS_URI=file:///cyclonedds.xml
  #   volumes:
  #     - ./cyclonedds.xml:/cyclonedds.xml
  #   privileged: true
  #   devices:
  #     - /dev/rplidar:/dev/rplidar

networks:
  ros_network:
    driver: bridge
