services:

  kobuki:
    image: crl/kobuki:humble
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ros2 launch kobuki kobuki.launch.py
    restart: unless-stopped
    privileged: true

    networks:
      - ros_network
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/cyclonedds.xml
    devices:
      - /dev:/dev

  lidar_node:
    build:
      context: .
      dockerfile: lidar.Dockerfile
    networks:
      - ros_network
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/cyclonedds.xml
    privileged: true
    devices:
      - /dev:/dev
    # Unsure if we need UDEV rules for lidar, if so, add them to the Dockerfile
    #   - "/dev/ttyUSB0:/dev/ttyUSB0" # CHANGE /dev/ttyUSB0 if your lidar is on a different port

networks:
 ros_network:
   driver: bridge